-- VHDL wrapper for NiFpgaAG_LabVIEW_Echo
-- Generated by LabVIEW FPGA IP Export Utility
--
-- Ports:
-- reset      :  Reset port. Minimum assertion length: 1 base clock cycles.
--               Minimum de-assertion length: 40 base clock cycles.
-- enable_in  :  Enable in port. Minimum re-initialization length: 7 base clock cycles.
-- enable_out :  Enable out port.
-- enable_clr :  Enable clear port.
-- ctrlind_00_Data_in_U8 : Top level control "Data_in (U8)", sync to Clk40, u8
-- ctrlind_01_Data_out_U8 : Top level indicator "Data_out (U8)", sync to Clk40, u8
-- Clk40 : Clock "40 MHz Onboard Clock", nominal frequency 40.00 MHz, base clock

library ieee;
use ieee.std_logic_1164.all;

entity NiFpgaIPWrapper_LabVIEW_Echo is
		port (
			reset : in std_logic;
			enable_in : in std_logic;
			enable_out : out std_logic;
			enable_clr : in std_logic;
			ctrlind_00_Data_in_U8 : in std_logic_vector(7 downto 0);
			ctrlind_01_Data_out_U8 : out std_logic_vector(7 downto 0);
			Clk40 : in std_logic
		);
end NiFpgaIPWrapper_LabVIEW_Echo;

architecture vhdl_labview of NiFpgaIPWrapper_LabVIEW_Echo is

	component NiFpgaAG_LabVIEW_Echo
		port (
			reset : in std_logic;
			enable_in : in std_logic;
			enable_out : out std_logic;
			enable_clr : in std_logic;
			ctrlind_00_Data_in_U8 : in std_logic_vector(7 downto 0);
			ctrlind_01_Data_out_U8 : out std_logic_vector(7 downto 0);
			Clk40 : in std_logic;
			tDiagramEnableOut : in std_logic
		);
	end component;

begin
	MyLabVIEWIP : NiFpgaAG_LabVIEW_Echo
		port map(
			reset => reset,
			enable_in => enable_in,
			enable_out => enable_out,
			enable_clr => enable_clr,
			ctrlind_00_Data_in_U8 => ctrlind_00_Data_in_U8,
			ctrlind_01_Data_out_U8 => ctrlind_01_Data_out_U8,
			Clk40 => Clk40,
			tDiagramEnableOut => '1'
		);

end vhdl_labview;

